// <auto-generated />
using System;
using CP.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CP.Server.Migrations
{
    [DbContext(typeof(CarParkContext))]
    [Migration("20260503101325_InitialCreate_CarPark")]
    partial class InitialCreate_CarPark
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles", "public", t =>
                        {
                            t.HasTrigger("AspNetRoles_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "public", t =>
                        {
                            t.HasTrigger("AspNetRoleClaims_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", "public", t =>
                        {
                            t.HasTrigger("AspNetUsers_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "public", t =>
                        {
                            t.HasTrigger("AspNetUserClaims_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "public", t =>
                        {
                            t.HasTrigger("AspNetUserLogins_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "public", t =>
                        {
                            t.HasTrigger("AspNetUserRoles_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "public", t =>
                        {
                            t.HasTrigger("AspNetUserTokens_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DriverId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("true");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("license_expiry_date");

                    b.Property<DateTime>("LicenseIssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("license_issue_date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_number");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("DriverId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("drivers", "public", t =>
                        {
                            t.HasTrigger("drivers_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripId"));

                    b.Property<decimal?>("EndOdometer")
                        .HasPrecision(12, 1)
                        .HasColumnType("numeric(12,1)")
                        .HasColumnName("end_odometer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<decimal>("StartOdometer")
                        .HasPrecision(12, 1)
                        .HasColumnType("numeric(12,1)")
                        .HasColumnName("start_odometer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'planned'::character varying");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trip_date");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("TripId");

                    b.HasIndex("RequestId");

                    b.HasIndex("VehicleId");

                    b.ToTable("trips", "public", t =>
                        {
                            t.HasTrigger("trips_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.TripRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("RequestId");

                    b.HasIndex("DriverId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("trip_requests", "public", t =>
                        {
                            t.HasTrigger("trip_requests_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("true");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasTrigger("users_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.VDriver", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ДатаВыдачиПрав")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Дата_выдачи_прав");

                    b.Property<DateTime?>("ДатаОкончанияПрав")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Дата_окончания_прав");

                    b.Property<DateTime?>("ДатаРождения")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Дата_рождения");

                    b.Property<int?>("ИдентификаторВодителя")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_водителя");

                    b.Property<string>("Имя")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("НомерПрав")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Номер_прав");

                    b.Property<string>("Отчество")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("Состояние")
                        .HasColumnType("boolean");

                    b.Property<string>("Телефон")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Фамилия")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.ToTable("v_drivers", "public", t =>
                        {
                            t.HasTrigger("v_drivers_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.VTrip", b =>
                {
                    b.Property<DateTime?>("ВремяНачала")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Время_начала");

                    b.Property<DateTime?>("ВремяОкончания")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Время_окончания");

                    b.Property<DateTime?>("ДатаПоездки")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Дата_поездки");

                    b.Property<int?>("ИдентификаторЗаявки")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_заявки");

                    b.Property<int?>("ИдентификаторПоездки")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_поездки");

                    b.Property<int?>("ИдентификаторТс")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_ТС");

                    b.Property<decimal?>("ПробегВКонце")
                        .HasPrecision(12, 1)
                        .HasColumnType("numeric(12,1)")
                        .HasColumnName("Пробег_в_конце");

                    b.Property<decimal?>("ПробегВНачале")
                        .HasPrecision(12, 1)
                        .HasColumnType("numeric(12,1)")
                        .HasColumnName("Пробег_в_начале");

                    b.Property<string>("Статус")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.ToTable("v_trips", "public", t =>
                        {
                            t.HasTrigger("v_trips_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.VTripRequest", b =>
                {
                    b.Property<DateTime?>("ДатаСоздания")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Дата_создания");

                    b.Property<int?>("ИдентификаторВодителя")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_водителя");

                    b.Property<int?>("ИдентификаторЗаявки")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_заявки");

                    b.Property<int?>("ИдентификаторПользователя")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_пользователя");

                    b.Property<int?>("ИдентификаторТс")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_ТС");

                    b.Property<string>("Описание")
                        .HasColumnType("text");

                    b.Property<string>("Статус")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.ToTable("v_trip_requests", "public", t =>
                        {
                            t.HasTrigger("v_trip_requests_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.VUser", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ИдентификаторПользователя")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор пользователя");

                    b.Property<string>("ИмяПользователя")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Имя_пользователя");

                    b.Property<string>("Роль")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("Состояние")
                        .HasColumnType("boolean");

                    b.Property<string>("ХэшПароля")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Хэш_пароля");

                    b.ToTable("v_users", "public", t =>
                        {
                            t.HasTrigger("v_users_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.VVehicle", b =>
                {
                    b.Property<string>("VinНомер")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("VIN_номер");

                    b.Property<int?>("ГодВыпуска")
                        .HasColumnType("integer")
                        .HasColumnName("Год_выпуска");

                    b.Property<string>("Госномер")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int?>("ИдентификаторВодителя")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_водителя");

                    b.Property<int?>("ИдентификаторТс")
                        .HasColumnType("integer")
                        .HasColumnName("Идентификатор_ТС");

                    b.Property<string>("Марка")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Модель")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Пробег")
                        .HasPrecision(12, 1)
                        .HasColumnType("numeric(12,1)");

                    b.Property<string>("Состояние")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Страховка")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ТипТоплива")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Тип_топлива");

                    b.Property<string>("ТипТс")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Тип_ТС");

                    b.ToTable("v_vehicles", "public", t =>
                        {
                            t.HasTrigger("v_vehicles_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<string>("FuelType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("Insurance")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("insurance");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("license_plate");

                    b.Property<decimal?>("Mileage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 1)
                        .HasColumnType("numeric(12,1)")
                        .HasColumnName("mileage")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vehicle_type");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("VehicleId");

                    b.HasIndex("DriverId");

                    b.ToTable("vehicles", "public", t =>
                        {
                            t.HasTrigger("vehicles_Trigger");
                        });
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetRoleClaim", b =>
                {
                    b.HasOne("CP.Server.Models.CarPark.AspNetRole", "AspNetRole")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetRole");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUserClaim", b =>
                {
                    b.HasOne("CP.Server.Models.CarPark.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUserLogin", b =>
                {
                    b.HasOne("CP.Server.Models.CarPark.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUserRole", b =>
                {
                    b.HasOne("CP.Server.Models.CarPark.AspNetRole", "AspNetRole")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CP.Server.Models.CarPark.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetRole");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUserToken", b =>
                {
                    b.HasOne("CP.Server.Models.CarPark.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.Driver", b =>
                {
                    b.HasOne("CP.Server.Models.CarPark.User", "User")
                        .WithMany("Drivers")
                        .HasForeignKey("UserId");

                    b.HasOne("CP.Server.Models.CarPark.Vehicle", "Vehicle")
                        .WithMany("Drivers")
                        .HasForeignKey("VehicleId");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.Trip", b =>
                {
                    b.HasOne("CP.Server.Models.CarPark.TripRequest", "TripRequest")
                        .WithMany("Trips")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CP.Server.Models.CarPark.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripRequest");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.TripRequest", b =>
                {
                    b.HasOne("CP.Server.Models.CarPark.Driver", "Driver")
                        .WithMany("TripRequests")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CP.Server.Models.CarPark.User", "User")
                        .WithMany("TripRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CP.Server.Models.CarPark.Vehicle", "Vehicle")
                        .WithMany("TripRequests")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.Vehicle", b =>
                {
                    b.HasOne("CP.Server.Models.CarPark.Driver", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");

                    b.Navigation("AspNetUserRoles");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserRoles");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.Driver", b =>
                {
                    b.Navigation("TripRequests");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.TripRequest", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.User", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("TripRequests");
                });

            modelBuilder.Entity("CP.Server.Models.CarPark.Vehicle", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("TripRequests");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
